image:
    - Visual Studio 2022
    - Visual Studio 2019

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc.cmake
shallow_clone: true             

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - CPP_STD: 17
          QT_MAJOR: 5
        - CPP_STD: 17
          QT_MAJOR: 6          
        - CPP_STD: 20
          QT_MAJOR: 5
        - CPP_STD: 20
          QT_MAJOR: 6

matrix:
    fast_finish: false
    exclude:
        - platform: x86
          QT_MAJOR: 6          
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - mkdir "%BUILD_DIR%"

build_script:
    - echo ------------------------- Building Project -------------------------
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%CMAKE_GENERATOR%" -A %CMAKE_PLATFORM% ^
        -DCMAKE_INSTALL_PREFIX="%BUILD_DIR%\install" ^
        -DCMAKE_PREFIX_PATH="%QTDIR%" -DCMAKE_CXX_STANDARD=%CPP_STD% ^
        -DBOOST_ROOT="%BOOST_DIR%" -DBoost_USE_STATIC_LIBS=ON ^
        -DCMAKE_PROJECT_INCLUDE=config/All.cmake -DOPT_QT_MAJOR_VERSION=%QT_MAJOR% ^
        -DOPT_CC_UBLOX_PROTOCOL_CC_TOOLS_PLUGIN=OFF
    - cmake --build . --config %CONFIGURATION% 
    - echo -------------------------- Deploying Qt ---------------------------
    - cmake --build . --config %CONFIGURATION% --target deploy_qt

