include (${PROJECT_SOURCE_DIR}/config/All.cmake)

macro (set_develop_branch name)
    if (NOT DEFINED ${name}_GIT_TAG)
        set (${name}_GIT_TAG "develop")
    endif ()
endmacro ()

set_develop_branch (COMMS)
set_develop_branch (CC_TOOLS_QT)
set_develop_branch (COMMSDSL)
set_develop_branch (CC_DEMO1_GENERATED)
set_develop_branch (CC_DEMO2_GENERATED)
set_develop_branch (CC_DEMO3_GENERATED)
set_develop_branch (CC_MQTT311_GENERATED)
set_develop_branch (CC_MQTT5_GENERATED)
set_develop_branch (CC_MQTTSN_GENERATED)
set_develop_branch (CC_UBLOX_GENERATED)
set_develop_branch (CC_X509_GENERATED)
set_develop_branch (CC_MQTTSN_LIBS)
set_develop_branch (CC_MQTT311_LIBS)
set_develop_branch (CC_MQTT5_LIBS)
set_develop_branch (CC_DEMO1_PROTOCOL_CC_TOOLS_PLUGIN)
set_develop_branch (CC_DEMO2_PROTOCOL_CC_TOOLS_PLUGIN)
set_develop_branch (CC_DEMO3_PROTOCOL_CC_TOOLS_PLUGIN)
set_develop_branch (CC_MQTT311_PROTOCOL_CC_TOOLS_PLUGIN)
set_develop_branch (CC_MQTT5_PROTOCOL_CC_TOOLS_PLUGIN)
set_develop_branch (CC_MQTTSN_PROTOCOL_CC_TOOLS_PLUGIN)
set_develop_branch (CC_UBLOX_PROTOCOL_CC_TOOLS_PLUGIN)
set_develop_branch (CC_MQTT311_CLIENT_FILTER_CC_TOOLS_PLUGIN)
set_develop_branch (CC_MQTT5_CLIENT_FILTER_CC_TOOLS_PLUGIN)
