macro (enable_if_opt_not_set name)
    if (NOT DEFINED ${name})
        set (${name} ON)
    endif ()
endmacro()

enable_if_opt_not_set (OPT_COMMS)
enable_if_opt_not_set (OPT_COMMSDSL)
enable_if_opt_not_set (OPT_CC_DEMO1_GENERATED)
enable_if_opt_not_set (OPT_CC_DEMO2_GENERATED)
enable_if_opt_not_set (OPT_CC_DEMO3_GENERATED)
enable_if_opt_not_set (OPT_CC_MQTT311_GENERATED)
enable_if_opt_not_set (OPT_CC_MQTT5_GENERATED)
enable_if_opt_not_set (OPT_CC_MQTTSN_GENERATED)
enable_if_opt_not_set (OPT_CC_UBLOX_GENERATED)
enable_if_opt_not_set (OPT_CC_X509_GENERATED)
enable_if_opt_not_set (OPT_CC_MQTTSN_LIBS)
enable_if_opt_not_set (OPT_CC_MQTT311_LIBS)
enable_if_opt_not_set (OPT_CC_MQTT5_LIBS)