macro (enalbe_if_opt_not_set name)
    if (NOT DEFINED ${name})
        set (${name} ON)
    endif ()
endmacro()

enalbe_if_opt_not_set (OPT_CC_DEMO1_GENERATED)
enalbe_if_opt_not_set (OPT_CC_DEMO2_GENERATED)
enalbe_if_opt_not_set (OPT_CC_DEMO3_GENERATED)
enalbe_if_opt_not_set (OPT_CC_MQTT311_GENERATED)
enalbe_if_opt_not_set (OPT_CC_MQTT5_GENERATED)
enalbe_if_opt_not_set (OPT_CC_MQTTSN_GENERATED)
enalbe_if_opt_not_set (OPT_CC_UBLOX_GENERATED)
enalbe_if_opt_not_set (OPT_CC_X509_GENERATED)