macro (enalbe_if_opt_not_set name)
    if (NOT DEFINED ${name})
        set (${name} ON)
    endif ()
endmacro()

enalbe_if_opt_not_set (OPT_CC_TOOLS_QT)
enalbe_if_opt_not_set (OPT_CC_DEMO1_PROTOCOL_CC_TOOLS_PLUGIN)
enalbe_if_opt_not_set (OPT_CC_DEMO2_PROTOCOL_CC_TOOLS_PLUGIN)
enalbe_if_opt_not_set (OPT_CC_DEMO3_PROTOCOL_CC_TOOLS_PLUGIN)
enalbe_if_opt_not_set (OPT_CC_MQTT311_PROTOCOL_CC_TOOLS_PLUGIN)
enalbe_if_opt_not_set (OPT_CC_MQTT5_PROTOCOL_CC_TOOLS_PLUGIN)
enalbe_if_opt_not_set (OPT_CC_MQTTSN_PROTOCOL_CC_TOOLS_PLUGIN)
enalbe_if_opt_not_set (OPT_CC_UBLOX_PROTOCOL_CC_TOOLS_PLUGIN)
enalbe_if_opt_not_set (OPT_CC_MQTT5_CLIENT_FILTER_CC_TOOLS_PLUGIN)