macro (enable_if_opt_not_set name)
    if (NOT DEFINED ${name})
        set (${name} ON)
    endif ()
endmacro()

enable_if_opt_not_set (OPT_COMMS)
enable_if_opt_not_set (OPT_CC_TOOLS_QT)
enable_if_opt_not_set (OPT_COMMSDSL)
enable_if_opt_not_set (OPT_CC_MQTT311_GENERATED)
enable_if_opt_not_set (OPT_CC_MQTT5_GENERATED)
enable_if_opt_not_set (OPT_CC_MQTTSN_GENERATED)
enable_if_opt_not_set (OPT_CC_UBLOX_GENERATED)
enable_if_opt_not_set (OPT_CC_X509_GENERATED)
enable_if_opt_not_set (OPT_CC_MQTTSN_LIBS)
enable_if_opt_not_set (OPT_CC_MQTT311_LIBS)
enable_if_opt_not_set (OPT_CC_MQTT5_LIBS)
enable_if_opt_not_set (OPT_CC_MQTT311_PROTOCOL_CC_TOOLS_PLUGIN)
enable_if_opt_not_set (OPT_CC_MQTT5_PROTOCOL_CC_TOOLS_PLUGIN)
enable_if_opt_not_set (OPT_CC_MQTTSN_PROTOCOL_CC_TOOLS_PLUGIN)
enable_if_opt_not_set (OPT_CC_UBLOX_PROTOCOL_CC_TOOLS_PLUGIN)
enable_if_opt_not_set (OPT_CC_MQTT311_CLIENT_FILTER_CC_TOOLS_PLUGIN)
enable_if_opt_not_set (OPT_CC_MQTT5_CLIENT_FILTER_CC_TOOLS_PLUGIN)
enable_if_opt_not_set (OPT_CC_MQTTSN_CLIENT_FILTER_CC_TOOLS_PLUGIN)

list (APPEND CC_TOOLS_QT_CMAKE_ARGS
    -DCC_TOOLS_QT_WARN_AS_ERR=OFF
    -DCC_TOOLS_QT_MAJOR_QT_VERSION=6
)

list (APPEND COMMSDSL_CMAKE_ARGS
    -DCOMMSDSL_BUILD_COMMSDSL2TEST=ON
    -DCOMMSDSL_BUILD_COMMSDSL2TOOLS_QT=ON
    -DCOMMSDSL_BUILD_COMMSDSL2SWIG=ON
    -DCOMMSDSL_BUILD_COMMSDSL2EMSCRIPTEN=ON
    -DCOMMSDSL_BUILD_COMMSDSL2LATEX=ON
    -DCOMMSDSL_BUILD_COMMSDSL2C=ON
    -DCOMMSDSL_BUILD_COMMSDSL2WIRESHARK=ON
    -DCOMMSDSL_INSTALL_LIBRARY=ON
    -DCOMMSDSL_WARN_AS_ERR=OFF
)

list (APPEND CC_MQTTSN_LIBS_CMAKE_ARGS
    -DCC_MQTTSN_WARN_AS_ERR=OFF
    -DBUILD_SHARED_LIBS=ON
)

list (APPEND CC_MQTT311_LIBS_CMAKE_ARGS
    -DCC_MQTT311_WARN_AS_ERR=OFF
    -DBUILD_SHARED_LIBS=ON
)

list (APPEND CC_MQTT5_LIBS_CMAKE_ARGS
    -DCC_MQTT5_WARN_AS_ERR=OFF
    -DBUILD_SHARED_LIBS=ON
)

list (APPEND CC_MQTTSN_PROTOCOL_CC_TOOLS_PLUGIN_CMAKE_ARGS
    -DOPT_WARN_AS_ERR=OFF
    -DOPT_QT_MAJOR_VERSION=6
)

list (APPEND CC_MQTT311_PROTOCOL_CC_TOOLS_PLUGIN_CMAKE_ARGS
    -DOPT_WARN_AS_ERR=OFF
    -DOPT_QT_MAJOR_VERSION=6
)

list (APPEND CC_MQTT5_PROTOCOL_CC_TOOLS_PLUGIN_CMAKE_ARGS
    -DOPT_WARN_AS_ERR=OFF
    -DOPT_QT_MAJOR_VERSION=6
)

list (APPEND CC_UBLOX_PROTOCOL_CC_TOOLS_PLUGIN_CMAKE_ARGS
    -DOPT_WARN_AS_ERR=OFF
    -DOPT_QT_MAJOR_VERSION=6
)

list (APPEND CC_MQTT311_CLIENT_FILTER_CC_TOOLS_PLUGIN_CMAKE_ARGS
    -DOPT_WARN_AS_ERR=OFF
    -DOPT_QT_MAJOR_VERSION=6
)

list (APPEND CC_MQTT5_CLIENT_FILTER_CC_TOOLS_PLUGIN_CMAKE_ARGS
    -DOPT_WARN_AS_ERR=OFF
    -DOPT_QT_MAJOR_VERSION=6
)

list (APPEND CC_MQTTSN_CLIENT_FILTER_CC_TOOLS_PLUGIN_CMAKE_ARGS
    -DOPT_WARN_AS_ERR=OFF
    -DOPT_QT_MAJOR_VERSION=6
)

set (OPT_EXTERNALS_DIR "${PROJECT_BINARY_DIR}/externals")