#!/bin/bash

ROOT_DIR=$(dirname $(realpath $0))

function usage {
    echo "Usage: ${0} <cmd> <options...>"
    echo
    ls -al "${ROOT_DIR}/*"
    echo "Available cmds:"
    for f in ${ROOT_DIR}/cc/bin/*; do
        cmd=$(basename ${f})
        echo "    ${cmd}"
    done
    echo 
    echo "Use \"${0} <cmd> -h\" to inquire about command options"
}

CMD=${1}
if [ -z "${CMD}" ]; then
    usage
    exit 0
fi

APP="${ROOT_DIR}/cc/bin/${CMD}"
if [ ! -e "${APP}" ]; then
    echo "ERROR: Command ${CMD} is not available"
    usage
    exit 1
fi

shift

export LD_LIBRARY_PATH=${ROOT_DIR}/cc/lib:${LD_LIBRARY_PATH}
exec ${APP} "$@"